# This is ingress controller by Nginx Inc. Details at https://github.com/nginxinc/kubernetes-ingress
# This file creates Ingress Controller as a Deployment. A Daemon-Set is also possible.
# Ingress Controller for public namespace ontrack-pub. Ingress Controller itself is residing in ingress-controller namespace

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config-pub
  namespace: vendor-tooling
data:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-pub
  namespace: vendor-tooling
spec:
  selector:
    matchLabels:
      app: nginx-ingress-pub
  template:
    metadata:
      labels:
        app: nginx-ingress-pub
    spec:
      serviceAccountName: nginx-ingress-pub
      containers:
      - image: nginx/nginx-ingress:1.3.0
        imagePullPolicy: Always
        name: nginx-ingress-pub
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        env:
        - name: nginx_pub
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: nginx_public
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=nginx_pub/nginx-config-pub
          - -default-server-tls-secret=nginx_pub/default-server-secret-pub
          - -ingress-class=ontrack-pub
          - -watch-namespace=ontrack-pub
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-pub
  namespace: vendor-tooling
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress-pub


